# created by wich

from .. import loader, utils
from asyncio import sleep

@loader.tds
class MolitvaMod(loader.Module):
	"""Мем (Молитва)"""
	strings = {'name': 'Molitva'}
	@loader.owner
	async def molitvacmd(self, message_id):
	"""старт"""
    await utils.answer(message, ' О, Великий Аккумулятор,')
    await asyncio.sleep(7)
    await utils.answer(message, ' отец анода и катода.')
    await asyncio.sleep(7)
    await utils.answer(message, ' Дай силы стартеру,')
    await asyncio.sleep(7)
    await utils.answer(message, ' чтоб бендикс его зашел')
    await asyncio.sleep(7)
    await utils.answer(message, ' в зацепление с маховика венцом')
    await asyncio.sleep(7)
    await utils.answer(message, ' Чтоб прокрутил его ')
    await asyncio.sleep(7)
    await utils.answer(message, ' и коленвал с ним общими болтами связанный')
    await asyncio.sleep(7)
    await utils.answer(message, ' Дабы поршень суетливый забегал в цилиндре,')
    await asyncio.sleep(7)
    await utils.answer(message, ' давно уж ход потерявшим.')
    await asyncio.sleep(7)
    await utils.answer(message, ' И еще прошу тебя, дай искру мощную,')
    await asyncio.sleep(7)
    await utils.answer(message, ' на свечи старые, жизнь видавшие')
    await asyncio.sleep(7)
    await utils.answer(message, ' Чтоб вспыхнул огонь святой,')
    await asyncio.sleep(7)
    await utils.answer(message, ' в камере сгорания.')
    await asyncio.sleep(7)
    await utils.answer(message, ' Огонь от воспламенения жидкости горючей,')
    await asyncio.sleep(7)
    await utils.answer(message, ' уставшими форсунками впрыснутой.')
    await asyncio.sleep(7)
    await utils.answer(message, ' Пусть клапан неплотно к седлу прилегающий,')
    await asyncio.sleep(7)
    await utils.answer(message, ' откроется во время ему предначертанное,')
    await asyncio.sleep(7)
    await utils.answer(message, ' Пусть удары судьбы выдержит ремень зубчатый,')
    await asyncio.sleep(7)
    await utils.answer(message, ' на шкивы ГРМ одетый.')
    await asyncio.sleep(7)
    await utils.answer(message, ' Да начнет вращаться вал коленчатый,')
    await asyncio.sleep(7)
    await utils.answer(message, ' во вкладышах лежащий и привод его к насосу масляному,')
    await asyncio.sleep(7)
    await utils.answer(message, ' Чтоб подавал он жидкость,')
    await asyncio.sleep(7)
    await utils.answer(message, ' жизнь продляющую, деталям страждущим,')
    await asyncio.sleep(7)
    await utils.answer(message, ' всю жизнь которые на одном месте вертятся,')
    await asyncio.sleep(7)
    await utils.answer(message, ' себя не жалея, жизнь ведя праведную.')
    await asyncio.sleep(7)
    await utils.answer(message, ' Прошу, чтоб в семье большой, ')
    await asyncio.sleep(7)
    await utils.answer(message, ' которая ДВС зовется, разлада не было.')
    await asyncio.sleep(7)
    await utils.answer(message, ' Не приходил к ним Check engine,')
    await asyncio.sleep(7)
    await utils.answer(message, ' святым ДМРВ, проклятый.')
    await asyncio.sleep(7)
    await utils.answer(message, ' И проснется под капотом зверь спящий,')
    await asyncio.sleep(7)
    await utils.answer(message, ' голосом зычным обладающий')
    await asyncio.sleep(7)
    await utils.answer(message, ' Возвестит округу сонную,')
    await asyncio.sleep(7)
    await utils.answer(message, ' выхлопным трактом порванным, о своем пробуждении.')
    await asyncio.sleep(7)
    await utils.answer(message, ' И пусть боятся зверя этого,')
    await asyncio.sleep(7)
    await utils.answer(message, ' грешники, на СТО работающие.')
    await asyncio.sleep(7)
    await utils.answer(message, ' Зверя сильного, мной прирученного. ')
    await asyncio.sleep(7)
    await utils.answer(message, ' Аминь🙏')
