# created by wich

from .. import loader
from asyncio import sleep

@loader.tds
class MolitvaMod(loader.Module):
	"""Мем (Молитва)"""
	strings = {'name': 'Molitva'}
	@loader.owner
	async def molitvacmd(self, message_id):
	"""старт"""
    await message_id.edit(' О, Великий Аккумулятор,')
    await asyncio.sleep(7)
    await message_id.edit(' отец анода и катода.')
    await asyncio.sleep(7)
    await message_id.edit(' Дай силы стартеру,')
    await asyncio.sleep(7)
    await message_id.edit(' чтоб бендикс его зашел')
    await asyncio.sleep(7)
    await message_id.edit(' в зацепление с маховика венцом')
    await asyncio.sleep(7)
    await message_id.edit(' Чтоб прокрутил его ')
    await asyncio.sleep(7)
    await message_id.edit(' и коленвал с ним общими болтами связанный')
    await asyncio.sleep(7)
    await message_id.edit(' Дабы поршень суетливый забегал в цилиндре,')
    await asyncio.sleep(7)
    await message_id.edit(' давно уж ход потерявшим.')
    await asyncio.sleep(7)
    await message_id.edit(' И еще прошу тебя, дай искру мощную,')
    await asyncio.sleep(7)
    await message_id.edit(' на свечи старые, жизнь видавшие')
    await asyncio.sleep(7)
    await message_id.edit(' Чтоб вспыхнул огонь святой,')
    await asyncio.sleep(7)
    await message_id.edit(' в камере сгорания.')
    await asyncio.sleep(7)
    await message_id.edit(' Огонь от воспламенения жидкости горючей,')
    await asyncio.sleep(7)
    await message_id.edit(' уставшими форсунками впрыснутой.')
    await asyncio.sleep(7)
    await message_id.edit(' Пусть клапан неплотно к седлу прилегающий,')
    await asyncio.sleep(7)
    await message_id.edit(' откроется во время ему предначертанное,')
    await asyncio.sleep(7)
    await message_id.edit(' Пусть удары судьбы выдержит ремень зубчатый,')
    await asyncio.sleep(7)
    await message_id.edit(' на шкивы ГРМ одетый.')
    await asyncio.sleep(7)
    await message_id.edit(' Да начнет вращаться вал коленчатый,')
    await asyncio.sleep(7)
    await message_id.edit(' во вкладышах лежащий и привод его к насосу масляному,')
    await asyncio.sleep(7)
    await message_id.edit(' Чтоб подавал он жидкость,')
    await asyncio.sleep(7)
    await message_id.edit(' жизнь продляющую, деталям страждущим,')
    await asyncio.sleep(7)
    await message_id.edit(' всю жизнь которые на одном месте вертятся,')
    await asyncio.sleep(7)
    await message_id.edit(' себя не жалея, жизнь ведя праведную.')
    await asyncio.sleep(7)
    await message_id.edit(' Прошу, чтоб в семье большой, ')
    await asyncio.sleep(7)
    await message_id.edit(' которая ДВС зовется, разлада не было.')
    await asyncio.sleep(7)
    await message_id.edit(' Не приходил к ним Check engine,')
    await asyncio.sleep(7)
    await message_id.edit(' святым ДМРВ, проклятый.')
    await asyncio.sleep(7)
    await message_id.edit(' И проснется под капотом зверь спящий,')
    await asyncio.sleep(7)
    await message_id.edit(' голосом зычным обладающий')
    await asyncio.sleep(7)
    await message_id.edit(' Возвестит округу сонную,')
    await asyncio.sleep(7)
    await message_id.edit(' выхлопным трактом порванным, о своем пробуждении.')
    await asyncio.sleep(7)
    await message_id.edit(' И пусть боятся зверя этого,')
    await asyncio.sleep(7)
    await message_id.edit(' грешники, на СТО работающие.')
    await asyncio.sleep(7)
    await message_id.edit(' Зверя сильного, мной прирученного. ')
    await asyncio.sleep(7)
    await message_id.edit(' Аминь🙏')
