#created by @wich

from .. import loader
from asyncio import sleep

@loader.tds
class WhatgayMod(loader.Module):
	"""Мем (Глухонемая хрень)"""
	strings = {'name': 'Whatgay'}
	@loader.owner
	async def whatgcmd(self, message_id):
	"""старт"""
		await message_id.edit("Приветствую")
		await asyncio.sleep(4)
		await message_id.edit("И напишу тебе сейчас хуйню.")
		await asyncio.sleep(4)
		await message_id.edit("А ты молчи, ведь ты всегда молчишь...")
		await asyncio.sleep(4)
		await message_id.edit("Глухонемая хрень, какого пола ты?")
		await asyncio.sleep(4)
		await message_id.edit("Не понять")
		await asyncio.sleep(2)
		await message_id.edit("Ты баба или страшный парень, блять?")
		await asyncio.sleep(4)
		await message_id.edit("На свиданку бы тебя позвать.,")
		await asyncio.sleep(4)
		await message_id.edit("Но вдруг ты все-таки парень?! -")
		await asyncio.sleep(4)
		await message_id.edit("Получится фигово...")
		await asyncio.sleep(3)
		await message_id.edit("Хотя...")
		await asyncio.sleep(2)
		await message_id.edit("Какая в жопу разница?")
		await asyncio.sleep(4)
		await message_id.edit("Если только в задницу...")
		await asyncio.sleep(4)
		await message_id.edit("Ведь безрыбье, блять...")
		await asyncio.sleep(4)
		await message_id.edit("Надеть пакет на голову -")
		await asyncio.sleep(4)
		await message_id.edit("И сойдешь за голума.")
		await asyncio.sleep(4)
		await message_id.edit("Стыдно показать...")
		await asyncio.sleep(3)
		await message_id.edit("Так скажи мне,")
		await asyncio.sleep(2)
		await message_id.edit("Есть ли хуй, есть ли хуй у тебя промеж ног?")
		await asyncio.sleep(5)
		await message_id.edit("Или все-таки пизда?")
		await asyncio.sleep(4)
		await message_id.edit("Ну скажи, ну скажи, ну скажи хоть слово,")
		await asyncio.sleep(5)
		await message_id.edit("Дура ебанутая!")
		await asyncio.sleep(3)
		await message_id.edit("Ну а коли ж парень ты - да похер!")
		await asyncio.sleep(4)
		await message_id.edit("Один раз - не пидарас!")
		await asyncio.sleep(4)
		await message_id.edit("Есть ли хуй, есть ли хуй у тебя промеж ног?")
		await asyncio.sleep(5)
		await message_id.edit("У меня вообще там кость!")
		await asyncio.sleep(4)
		await message_id.edit("И как бы не хотелось, даже очень,")
		await asyncio.sleep(4)
		await message_id.edit("Но до сих пор доходит спьяну туго:")
		await asyncio.sleep(4)
		await message_id.edit("То ли хуй свисает между прочим, ")
		await asyncio.sleep(4)
		await message_id.edit("То ли вновь пизда обвисла, сука...")
		await asyncio.sleep(4)	