#created by @wich

from .. import loader, utils
from asyncio import sleep

@loader.tds
class WhatgayMod(loader.Module):
	"""Мем (Глухонемая хрень)"""
	strings = {'name': 'Whatgay'}
	@loader.owner
	async def whatgcmd(self, message_id):
	"""старт"""
		await utils.answer(message, "Приветствую")
		await asyncio.sleep(4)
		await utils.answer(message, "И напишу тебе сейчас хуйню.")
		await asyncio.sleep(4)
		await utils.answer(message, "А ты молчи, ведь ты всегда молчишь...")
		await asyncio.sleep(4)
		await utils.answer(message, "Глухонемая хрень, какого пола ты?")
		await asyncio.sleep(4)
		await utils.answer(message, "Не понять")
		await asyncio.sleep(2)
		await utils.answer(message, "Ты баба или страшный парень, блять?")
		await asyncio.sleep(4)
		await utils.answer(message, "На свиданку бы тебя позвать.,")
		await asyncio.sleep(4)
		await utils.answer(message, "Но вдруг ты все-таки парень?! -")
		await asyncio.sleep(4)
		await utils.answer(message, "Получится фигово...")
		await asyncio.sleep(3)
		await utils.answer(message, "Хотя...")
		await asyncio.sleep(2)
		await utils.answer(message, "Какая в жопу разница?")
		await asyncio.sleep(4)
		await utils.answer(message, "Если только в задницу...")
		await asyncio.sleep(4)
		await utils.answer(message, "Ведь безрыбье, блять...")
		await asyncio.sleep(4)
		await utils.answer(message, "Надеть пакет на голову -")
		await asyncio.sleep(4)
		await utils.answer(message, "И сойдешь за голума.")
		await asyncio.sleep(4)
		await utils.answer(message, "Стыдно показать...")
		await asyncio.sleep(3)
		await utils.answer(message, "Так скажи мне,")
		await asyncio.sleep(2)
		await utils.answer(message, "Есть ли хуй, есть ли хуй у тебя промеж ног?")
		await asyncio.sleep(5)
		await utils.answer(message, "Или все-таки пизда?")
		await asyncio.sleep(4)
		await utils.answer(message, "Ну скажи, ну скажи, ну скажи хоть слово,")
		await asyncio.sleep(5)
		await utils.answer(message, "Дура ебанутая!")
		await asyncio.sleep(3)
		await utils.answer(message, "Ну а коли ж парень ты - да похер!")
		await asyncio.sleep(4)
		await utils.answer(message, "Один раз - не пидарас!")
		await asyncio.sleep(4)
		await utils.answer(message, "Есть ли хуй, есть ли хуй у тебя промеж ног?")
		await asyncio.sleep(5)
		await utils.answer(message, "У меня вообще там кость!")
		await asyncio.sleep(4)
		await utils.answer(message, "И как бы не хотелось, даже очень,")
		await asyncio.sleep(4)
		await utils.answer(message, "Но до сих пор доходит спьяну туго:")
		await asyncio.sleep(4)
		await utils.answer(message, "То ли хуй свисает между прочим, ")
		await asyncio.sleep(4)
		await utils.answer(message, "То ли вновь пизда обвисла, сука...")
		await asyncio.sleep(4)	